# Generated by Django 6.1.1 on 2026-09-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff'), ('admin', 'Admin')], default='staff', max_length=20),
        ),
    ]
