# Generated by Django 6.1.1 on 2026-09-25 08:37

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='Asia/Kuala_Lumpur', help_text='IANA time zone name, e.g. Asia/Kuala_Lumpur, Asia/Manila, Indian/Maldives.', max_length=64, validators=[accounts.models.validate_timezone]),
        ),
    ]
