# Generated by Django 6.1.1 on 2026-09-25 10:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkDoneCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ocn', models.CharField(max_length=50, verbose_name='OCN')),
            ],
            options={
                'ordering': ['name', 'ocn'],
                'constraints': [models.UniqueConstraint(fields=('name', 'ocn'), name='unique_site_ocn')],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_attachment', models.FileField(blank=True, upload_to='tickets/attachments/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('received_at', models.DateTimeField()),
                ('cms_next_ticket_no', models.CharField(max_length=50, verbose_name='CMS next ticket no')),
                ('ticket_type', models.CharField(choices=[('hardware', 'Hardware'), ('software', 'Software'), ('network', 'Network'), ('configuration', 'Configuration'), ('training', 'Training / How-to'), ('other', 'Other')], max_length=20)),
                ('incoming_channel', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email'), ('portal', 'Customer Portal'), ('remote_monitoring', 'Remote Monitoring Alert'), ('walk_in', 'Walk-in / On-site')], max_length=20)),
                ('is_forwarded', models.BooleanField(default=False)),
                ('cms_added_on', models.DateTimeField()),
                ('issue_description', models.TextField()),
                ('possible_root_cause', models.TextField(blank=True)),
                ('notes', models.TextField()),
                ('total_duration_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('is_pre', models.BooleanField(default=False, verbose_name='PRE')),
                ('resolution_verified_on', models.DateTimeField(blank=True, null=True)),
                ('cms_closed_on', models.DateTimeField(blank=True, null=True)),
                ('service_closed_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('cms_added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='added_tickets', to=settings.AUTH_USER_MODEL)),
                ('cms_closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_tickets', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tickets', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.customer')),
                ('forwarded_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='forwarded_tickets', to=settings.AUTH_USER_MODEL)),
                ('resolution_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_tickets', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.site')),
            ],
            options={
                'ordering': ['-received_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TicketActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('troubleshooting', 'Troubleshooting'), ('remote_support', 'Remote Support'), ('onsite_visit', 'On-site Visit'), ('escalation', 'Escalation'), ('follow_up', 'Follow-up'), ('training', 'Training')], max_length=20)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Computed from start/end when left empty.')),
                ('likely_cause', models.CharField(blank=True, max_length=255)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_activities', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='tickets.ticket')),
                ('work_done_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.workdonecode')),
            ],
            options={
                'verbose_name_plural': 'ticket activities',
                'ordering': ['start_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['-received_at'], name='tickets_tic_receive_c007ab_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['cms_closed_on'], name='tickets_tic_cms_clo_fc9796_idx'),
        ),
    ]
