# Generated by Django 6.1.1 on 2026-09-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketactivity',
            name='likely_cause',
        ),
        migrations.AddField(
            model_name='ticketactivity',
            name='is_likely_cause',
            field=models.BooleanField(default=False, help_text='Marks this activity as having identified the likely cause of the issue.', verbose_name='likely cause'),
        ),
    ]
