# Generated by Django 6.1.1 on 2026-09-25 15:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_activity_is_likely_cause'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text='ISO 3166-1 alpha-2, e.g. MY, SG, PH (stored uppercase).', max_length=2, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{2}$', 'Use the 2-letter ISO 3166-1 code, e.g. MY.')], verbose_name='ISO code')),
            ],
            options={
                'verbose_name_plural': 'countries',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='site',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='site',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='workdonecode',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='site',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='tickets.country'),
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('is_recurring_annually', models.BooleanField(default=True, help_text='Same month and day every year; the year of the date is then ignored.', verbose_name='recurs annually')),
                ('country', models.ForeignKey(blank=True, help_text='Leave empty for a global (company-wide) holiday.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='holidays', to='tickets.country')),
            ],
            options={
                'ordering': ['date', 'name'],
            },
        ),
    ]
