# Generated by Django 6.1.1 on 2026-09-26 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('working_hours', '0002_protect_work_log_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklogentry',
            name='note',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
