# Generated by Django 6.1.1 on 2026-09-26 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_lookups_country_holiday_site_fields'),
        ('working_hours', '0004_work_log_start_end_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklogentry',
            name='ticket_activity',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_log_entry', to='tickets.ticketactivity'),
        ),
    ]
