# Generated by Django 6.1.1 on 2026-09-26 17:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_lookups_country_holiday_site_fields'),
        ('working_hours', '0005_work_log_ticket_activity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='worklogentry',
            index=models.Index(fields=['date'], name='work_log_date_idx'),
        ),
    ]
