# Generated by Django 6.1.1 on 2026-09-27 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_username', models.CharField(blank=True, max_length=150)),
                ('action', models.CharField(choices=[('login', 'Signed in'), ('login_failed', 'Sign-in failed'), ('logout', 'Signed out'), ('ticket_created', 'Ticket created'), ('ticket_updated', 'Ticket updated'), ('ticket_closed', 'Ticket closed'), ('ticket_reopened', 'Ticket reopened'), ('ticket_activity_added', 'Activity added'), ('ticket_activity_removed', 'Activity removed'), ('work_log_created', 'Hours logged'), ('work_log_updated', 'Hours edited'), ('work_log_deleted', 'Hours deleted'), ('lookup_created', 'Lookup added'), ('lookup_updated', 'Lookup edited'), ('lookup_deleted', 'Lookup deleted'), ('user_created', 'User created'), ('user_updated', 'User edited'), ('user_deactivated', 'User deactivated'), ('user_reactivated', 'User reactivated'), ('user_role_changed', 'Role changed'), ('user_password_reset', 'Password reset')], max_length=40)),
                ('target_type', models.CharField(blank=True, max_length=40)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('target_label', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.CharField(blank=True, max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'audit log entry',
                'verbose_name_plural': 'audit log entries',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['action'], name='audit_action_idx'), models.Index(fields=['target_type', 'target_id'], name='audit_target_idx')],
            },
        ),
    ]
